name: wheels

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_wheels:
    name: Build Python wheels
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            windows-11-arm,
            macos-13,
            macos-latest,
          ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.python-version }}
          path: wheelhouse/*.whl
